### ISSUE TITLE
Currency not working?

### ISSUE THREAD

**Issue by andreva7** [MoneyTools/MyMoney.Net#128]
The CDN flags are gone on my canadian accounts
When I open the currency window, there are no entries in the table and I see no way to add any.

**Comment by clovett** [comment]
Very strange, no changes have been made in this area in months, this code hasn't changed since 2023 and there is no code in our repo for dropping the SQL Lite currency table. Are you using the SQL lite database or some other file format?  I wonder what happened here?  Do you have a backup copy of your money database that you can try and see if that one has currency info set properly?

**Comment by andreva7** [comment]
My date file is SQL lite.
Looking at backups, it looks like the currency table just lost the entry. I don't know why.
My DB file also became smaller , from 5 MB to 4 MB,  The file size had not changed in 2 years prior to this.
I can not repro this problem again so I am closing it.

**Comment by clovett** [comment]
weird 0 did MoneyFlutter or any other app touch the SQL lite file?

**Comment by andreva7** [comment]
Oh, yes. I tried, but I did not remember saving the file because I could not really open it successfully in the first place

**Comment by clovett** [comment]
might be worth doing a full sql database compare with some SQL lite tool to make sure you haven't lost anything else compared with your backups (nice job keeping backups!)
