### ISSUE TITLE
Latest stock price is wrong

### ISSUE THREAD

**Issue by andreva7** [MoneyTools/MyMoney.Net#14]
When I look at the contents of the history file, I see this:
The Close value on the last day is wrong, and it's the close value of the previous day.

<StockQuote Volume="17092464" Low="130.7100" High="131.9700" Close="131.4900" Open="131.4000" Date="2019-06-12T00:00:00"/>
<StockQuote Volume="17200848" Low="131.5600" High="132.6700" Close="132.3200" Open="131.9800" Date="2019-06-13T00:00:00"/>
<StockQuote Volume="17821703" Low="131.6400" High="133.7900" Close="132.4500" Open="132.2600" Date="2019-06-14T00:00:00"/>
<StockQuote Volume="13834378" Low="132.5300" High="133.7300" Close="132.8500" Open="132.6300" Date="2019-06-17T00:00:00"/>
<StockQuote Volume="22722134" Low="133.5700" High="135.2400" Close="132.8500" Open="134.1900" Date="2019-06-18T00:00:00" Symbol="MSFT"/>

**Comment by clovett** [comment]
Yes, it is a known issue.  The schema for “Global Quote” from AlphaVantage gives “previous close” not current close (presumably because for a given day where the market hasn’t closed yet there is no current close.

For example:
https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=msft&apikey=AFTRUSLF95EP94KA

Notice the schema only provides “previous close”.

So I probably need to do some fix ups to account for this but haven’t got around to it.

Now the “public async Task<StockQuoteHistory> DownloadHistory(string symbol)” function however gets open/close price for each day, so we probably could use that to fix up the history created by the Global Quotes.

-Chris.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by clovett** [comment]
I switched to https://[query2.finance.yahoo.com/v8/finance/chart/MSFT?interval=1d&range=1y](https://query2.finance.yahoo.com/v8/finance/chart/MSFT?interval=1d&range=1y) and so I think the stock quote info should be correct now.
